site_name: QuantDB
site_description: High-performance stock data toolkit with intelligent AKShare caching (import as 'qdb')
site_url: https://franksunye.github.io/quantdb/
repo_url: https://github.com/franksunye/quantdb
repo_name: franksunye/quantdb
copyright: "Copyright © 2025 Ye Sun"

use_directory_urls: true

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.copy
    - search.suggest
    - search.highlight

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite
  - tables

nav:
  - Home: index.md
  - Get Started: get-started.md
  - User Guide: user-guide.md
  - API Reference: api-reference.md
  - FAQ: faq.md
  - Changelog: changelog.md
